Vagrant.configure("2") do |config|
  # Configurações gerais
  box_image = "generic/ubuntu2204"
  ssh_private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/windows']
  ssh_pub_key = "~/.ssh/authorized_keys"
  
  master_cpus = 2
  master_memory = "4096"
  
  worker_cpus = 2
  worker_memory = "2048"
  path_provision_cluster = "./provision/provision.sh"
  
  # Função para configurar cada nó
  def setup_node(config, name, ip, cpus, memory, box_image, ssh_private_key_path, ssh_pub_key, path_provision_cluster)
    config.vm.define name do |node|
      node.vm.box = box_image
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip

      node.ssh.insert_key = false
      node.ssh.private_key_path = ssh_private_key_path
      node.vm.provision "file", source: "~/.ssh/windows.pub", destination: ssh_pub_key

      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = cpus
        vb.memory = memory
      end

      # Provisionamento do cluster
      node.vm.provision "shell", path: path_provision_cluster
    end
  end

  # Configuração dos nós master
  (1..1).each do |i|
    setup_node(config, "master-#{i}", "172.89.0.1#{i}", master_cpus, master_memory, box_image, ssh_private_key_path, ssh_pub_key, path_provision_cluster)
  end

  # Configuração dos nós worker
  (1..2).each do |i|
    setup_node(config, "worker-#{i}", "172.89.0.1#{i+1}", worker_cpus, worker_memory, box_image, ssh_private_key_path, ssh_pub_key, path_provision_cluster)
  end
end
