# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "kind-cluster"
  config.vm.network "public_network", ip: "192.168.15.100"

  # Limitações de recursos
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096" # Memória em MB
    vb.cpus = 2        # Número de CPUs
    vb.gui = true
  end

  # Provisionamento
  config.vm.provision "shell", path: "provision/provision.sh"
end
